package Compiler;

import java.io.*;
import java.util.List;

/**
 * The Include class provides a method to execute a file with a specified command and
 * a list of numbers as arguments. This is for the part "include" of the project.
 */
public class Include {
    private String scriptPath;

    /**
     * Constructs an Include instance with the specified script path.
     *
     * @param scriptPath scriptPath the path to the script to be executed.
     */
    public Include(String scriptPath) {
        this.scriptPath = scriptPath;
    }

    /**
     * Executes the script with the specified command and the list of numbers as arguments.
     *
     * @param command the specified command, which can be "python", "gcc" etc...
     * @param numbers the numbers passed as arguments.
     * @return the output generated by the script.
     */
    public String executeScriptWithArgs(String command, List<Integer> numbers) {
        StringBuilder output = new StringBuilder();
        try {
            ProcessBuilder pb = new ProcessBuilder(command, scriptPath);
            pb.redirectErrorStream(true);
            Process execProcess = pb.start();

            // Provide the numbers in the list of numbers as arguments
            BufferedWriter writer = new BufferedWriter(new OutputStreamWriter(execProcess.getOutputStream()));
            for (Integer number : numbers) {
                writer.write(number.toString());
                writer.newLine();
            }
            writer.close();

            // Read the output of the executed script
            try (BufferedReader reader = new BufferedReader(new InputStreamReader(execProcess.getInputStream()))) {
                String line;
                while ((line = reader.readLine()) != null) {
                    output.append(line).append(System.lineSeparator());
                }
            }

            execProcess.waitFor();
        } catch (IOException | InterruptedException e) {
            e.printStackTrace();
        }
        return output.toString();
    }
}
